#!/bin/bash
# Git Flow Script para FairPadel Frontend

echo "🚀 Git Flow - FairPadel Frontend"
echo "================================="
echo ""
echo "Ramas disponibles:"
echo "  main    → Producción (deploy automático)"
echo "  develop → Staging (integración)"
echo "  feature/* → Nuevas funcionalidades"
echo "  hotfix/*  → Fixes urgentes a producción"
echo ""
echo "Comandos útiles:"
echo ""
echo "1. Crear nueva feature:"
echo "   git checkout develop"
echo "   git pull origin develop"
echo "   git checkout -b feature/nombre-feature"
echo "   git push -u origin feature/nombre-feature"
echo ""
echo "2. Mergear feature a develop:"
echo "   git checkout develop"
echo "   git pull origin develop"
echo "   git merge --no-ff feature/nombre-feature"
echo "   git push origin develop"
echo ""
echo "3. Crear PR a main (producción):"
echo "   git checkout develop"
echo "   git pull origin develop"
echo "   git checkout -b release/v1.x.x"
echo "   git push -u origin release/v1.x.x"
echo "   # Crear PR en GitHub a main"
echo ""
echo "4. Hotfix urgente:"
echo "   git checkout main"
echo "   git pull origin main"
echo "   git checkout -b hotfix/descripcion"
echo "   git push -u origin hotfix/descripcion"
echo "   # Crear PR a main"
echo ""
