[build]
builder = "nixpacks"
buildCommand = "cd v2/backend && npm install && npm run build"

[deploy]
startCommand = "cd v2/backend && npx prisma db push --accept-data-loss && npx prisma db seed && npm run start:prod"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
