[build]
builder = "nixpacks"
buildCommand = "cd v2/backend && npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "cd v2/backend && bash prisma/fix-db.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
